import { IEmployee } from "../interfaces/IEmployee";
import { workPosition } from "./enums/workPosition";

export function generateName(): string {
  const names: string[] =
    [
      'Lacey',
      'Kathy',
      'Amber',
      'Michelle',
      'Tim',
      'Mary',
      'Michael',
      'Bethany',
      'Elizabeth',
      'Brenda',
      'Dawn',
      'Mary',
      'Barbara',
      'Judy',
      'Anthony',
      'John',
      'David',
      'Debra',
      'Justin',
      'Tara',
      'Jonathon',
      'Dustin',
      'Amanda',
      'Bonnie',
      'Denise',
      'David',
      'Denise',
      'James',
      'Todd',
      'Carrie',
      'Daniel',
      'Mary',
      'Christopher',
      'Jennifer',
      'Jared',
      'David',
      'Christine',
      'Jason',
      'Jose',
      'John',
      'Katie',
      'Rita',
      'Krystal',
      'Emily',
      'Jose',
      'Robert',
      'Jeremy',
      'Crystal',
      'Virginia',
      'Angela',
      'Megan',
      'Andrew',
      'Kelsey',
      'Linda',
      'Jason',
      'William',
      'Mark',
      'Angel',
      'Jason',
      'Anita',
      'Jeffrey',
      'Monica',
      'Lisa',
      'Kimberly',
      'Walter',
      'Joshua',
      'Sara',
      'Christine',
      'Kathryn',
      'Nicole',
      'Lori',
      'Anthony',
      'Cameron',
      'Julie',
      'Austin',
      'William',
      'Michael',
      'Gina',
      'Melissa',
      'Kevin',
      'Christy',
      'James',
      'Sherry',
      'Pamela',
      'Victoria',
      'Mark',
      'Madison',
      'Maria',
      'Nancy',
      'Sherri',
      'Christian',
      'Desiree',
      'Timothy',
      'Robert',
      'Michelle',
      'Lee',
      'Kyle',
      'Christopher',
      'Shannon',
      'James',
    ];
  return names[Math.floor(Math.random()*100)];
}
export function generateSurname(): string {
  const surnames: string[] =
    [
      'Gonzalez',
      'Bautista',
      'Green',
      'Kidd',
      'Ayala',
      'Moore',
      'Davis',
      'Cook',
      'Barajas',
      'Taylor',
      'Kelly',
      'Brewer',
      'Baldwin',
      'Cook',
      'Harris',
      'Vazquez',
      'Yang',
      'Garrett',
      'Blake',
      'Williams',
      'Ramirez',
      'Scott',
      'Contreras',
      'Smith',
      'Rush',
      'Wagner',
      'Mcmillan',
      'Jennings',
      'Ferguson',
      'Carroll',
      'Chen',
      'Ray',
      'Coleman',
      'Snyder',
      'Sullivan',
      'Valentine',
      'Glover',
      'Adams',
      'Garcia',
      'Swanson',
      'Campbell',
      'Lin',
      'Hunt',
      'Stanley',
      'Nixon',
      'Blair',
      'Fowler',
      'Norris',
      'Herrera',
      'Andrews',
      'Bell',
      'Diaz',
      'Walker',
      'Bailey',
      'Wells',
      'Brooks',
      'Lawson',
      'Walker',
      'Mathews',
      'Pope',
      'Smith',
      'Griffin',
      'Ramirez',
      'Stewart',
      'Brown',
      'Sharp',
      'Yoder',
      'Barber',
      'Garrison',
      'Bowman',
      'Hall',
      'Wagner',
      'Collier',
      'Lane',
      'Graham',
      'Parker',
      'Hernandez',
      'Nelson',
      'Dunn',
      'Edwards',
      'Fuller',
      'Cook',
      'Wood',
      'Reed',
      'Duarte',
      'Peterson',
      'Joseph',
      'Newman',
      'Brewer',
      'Bailey',
      'Schultz',
      'Herrera',
      'Flores',
      'Edwards',
      'Gonzales',
      'Jenkins',
      'Barrett',
      'Vasquez',
      'Sanchez',
      'Smith'
    ];
  return surnames[Math.floor(Math.random()*100)];
}
export function generateWorkPosition(): string {
  return workPosition[Math.floor(Math.random()*6)]
}
export function generateDate() : Date { //Employee age would be 20-52 with this
  const startDate = new Date(1970,1,1);
  const endDate = new Date(2002,12,31);
  return new Date(startDate.getTime() + Math.random() * (endDate.getTime() - startDate.getTime()));
}
export function createNewEmployeeList(count: number) {
  let listOfEmployees: IEmployee[] = []
  for (let i = 0; i < count; i++) {
    listOfEmployees.push({
      id: i,
      name: generateName(),
      surname: generateSurname(),
      workPosition: generateWorkPosition(),
      dateOfBirth: generateDate()
    })
  }
  return listOfEmployees;
}